# Generated by Django 4.1 on 2023-08-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='secondary_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
