# Generated by Django 4.1 on 2023-09-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsites', '0003_destination_description_alter_destination_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='secondary_photo',
            new_name='second_photo',
        ),
        migrations.AddField(
            model_name='destination',
            name='third_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
