# Generated by Django 4.1 on 2023-09-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsites', '0004_rename_secondary_photo_destination_second_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcategory',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
